services:
  db:
    image: mysql:8.0
    container_name: mygame_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mygame_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: